namespace PaymentOperations.Api.Models;

// Payment Method DTOs
public class CreatePaymentMethodRequest
{
    public string Token { get; set; } // Token generated by Stripe.js on the frontend
    public string Type { get; set; } = "card"; // Defaults to "card"
}
